# Generated by Django 6.0.3 on 2026-03-04 12:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Phone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('permanent_address', models.TextField(blank=True, default='', help_text='Trvalé bydliště', verbose_name='Permanent address')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profile', to=settings.AUTH_USER_MODEL, verbose_name='User account')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'ordering': ['last_name', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlatOwner',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('share_numerator', models.PositiveIntegerField(default=1, help_text='Podíl — čitatel', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Share numerator')),
                ('share_denominator', models.PositiveIntegerField(default=1, help_text='Podíl — jmenovatel', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Share denominator')),
                ('effective_from', models.DateField(verbose_name='Effective from')),
                ('effective_to', models.DateField(blank=True, help_text='Leave blank if still active', null=True, verbose_name='Effective to')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flat_owners', to='flats.flat', verbose_name='Flat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flat_owners', to='owners.owner', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Flat ownership',
                'verbose_name_plural': 'Flat ownerships',
                'ordering': ['flat', '-effective_from'],
                'abstract': False,
                'unique_together': {('flat', 'owner', 'effective_from')},
            },
        ),
    ]
