# Generated by Django 5.2.12 on 2026-03-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_alter_flatowner_flat_alter_flatowner_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='cuzk_owner_id',
            field=models.BigIntegerField(blank=True, help_text='Identifikátor vlastníka v ISKN (ČÚZK)', null=True, verbose_name='CUZK owner ID'),
        ),
    ]
