# Generated by Django 6.0.3 on 2026-03-04 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Phone')),
                ('effective_from', models.DateField(verbose_name='Lease start')),
                ('effective_to', models.DateField(blank=True, help_text='Leave blank if still active', null=True, verbose_name='Lease end')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='flats.flat', verbose_name='Flat')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['flat', 'last_name'],
                'abstract': False,
            },
        ),
    ]
