# Generated by Django 6.0.3 on 2026-03-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='contact_address',
            field=models.TextField(blank=True, default='', help_text='Korespondenční adresa', verbose_name='Contact address'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='permanent_address',
            field=models.TextField(blank=True, default='', help_text='Trvalé bydliště', verbose_name='Permanent address'),
        ),
    ]
