from django.urls import path

from netbox.views.generic import ObjectChangeLogView

from . import models, views

urlpatterns = [
    path(
        "meeting-types/", views.MeetingTypeListView.as_view(), name="meetingtype_list"
    ),
    path(
        "meeting-types/add/",
        views.MeetingTypeEditView.as_view(),
        name="meetingtype_add",
    ),
    path(
        "meeting-types/delete/",
        views.MeetingTypeBulkDeleteView.as_view(),
        name="meetingtype_bulk_delete",
    ),
    path(
        "meeting-types/<int:pk>/", views.MeetingTypeView.as_view(), name="meetingtype"
    ),
    path(
        "meeting-types/<int:pk>/edit/",
        views.MeetingTypeEditView.as_view(),
        name="meetingtype_edit",
    ),
    path(
        "meeting-types/<int:pk>/delete/",
        views.MeetingTypeDeleteView.as_view(),
        name="meetingtype_delete",
    ),
    path(
        "meeting-types/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="meetingtype_changelog",
        kwargs={"model": models.MeetingType},
    ),
    path("meetings/", views.MeetingListView.as_view(), name="meeting_list"),
    path("meetings/add/", views.MeetingEditView.as_view(), name="meeting_add"),
    path(
        "meetings/delete/",
        views.MeetingBulkDeleteView.as_view(),
        name="meeting_bulk_delete",
    ),
    path("meetings/<int:pk>/", views.MeetingView.as_view(), name="meeting"),
    path(
        "meetings/<int:pk>/attendance/",
        views.MeetingAttendanceTabView.as_view(),
        name="meeting_attendance",
    ),
    path(
        "meetings/<int:pk>/agenda/",
        views.MeetingAgendaTabView.as_view(),
        name="meeting_agenda",
    ),
    path(
        "meetings/<int:pk>/ballots/",
        views.MeetingBallotsTabView.as_view(),
        name="meeting_ballots",
    ),
    path(
        "meetings/<int:pk>/start/",
        views.MeetingStartView.as_view(),
        name="meeting_start",
    ),
    path(
        "meetings/<int:pk>/finish/",
        views.MeetingFinishView.as_view(),
        name="meeting_finish",
    ),
    path(
        "meetings/<int:pk>/generate-invitation/",
        views.MeetingGenerateInvitationView.as_view(),
        name="meeting_generate_invitation",
    ),
    path(
        "meetings/<int:pk>/publish-invitation/",
        views.MeetingPublishInvitationView.as_view(),
        name="meeting_publish_invitation",
    ),
    path(
        "meetings/<int:pk>/toggle-attendance/",
        views.MeetingAttendanceToggleView.as_view(),
        name="meeting_toggle_attendance",
    ),
    path(
        "meetings/<int:pk>/refresh-snapshots/",
        views.MeetingRefreshSnapshotsView.as_view(),
        name="meeting_refresh_snapshots",
    ),
    path(
        "meetings/<int:pk>/agenda/add/",
        views.MeetingAgendaAddView.as_view(),
        name="meeting_agenda_add",
    ),
    path(
        "meetings/<int:pk>/agenda/move/",
        views.MeetingAgendaMoveView.as_view(),
        name="meeting_agenda_move",
    ),
    path(
        "meetings/<int:pk>/sync-ballot-types/",
        views.MeetingSyncBallotStylesView.as_view(),
        name="meeting_sync_ballot_types",
    ),
    path(
        "meetings/<int:pk>/export/",
        views.MeetingExportView.as_view(),
        name="meeting_export",
    ),
    path(
        "meetings/<int:pk>/edit/", views.MeetingEditView.as_view(), name="meeting_edit"
    ),
    path(
        "meetings/<int:pk>/delete/",
        views.MeetingDeleteView.as_view(),
        name="meeting_delete",
    ),
    path(
        "meetings/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="meeting_changelog",
        kwargs={"model": models.Meeting},
    ),
    path("agenda-items/", views.AgendaItemListView.as_view(), name="agendaitem_list"),
    path(
        "agenda-items/add/", views.AgendaItemEditView.as_view(), name="agendaitem_add"
    ),
    path(
        "agenda-items/delete/",
        views.AgendaItemBulkDeleteView.as_view(),
        name="agendaitem_bulk_delete",
    ),
    path("agenda-items/<int:pk>/", views.AgendaItemView.as_view(), name="agendaitem"),
    path(
        "agenda-items/<int:pk>/start-voting/",
        views.AgendaItemStartVotingView.as_view(),
        name="agendaitem_start_voting",
    ),
    path(
        "agenda-items/<int:pk>/edit/",
        views.AgendaItemEditView.as_view(),
        name="agendaitem_edit",
    ),
    path(
        "agenda-items/<int:pk>/delete/",
        views.AgendaItemDeleteView.as_view(),
        name="agendaitem_delete",
    ),
    path(
        "agenda-items/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="agendaitem_changelog",
        kwargs={"model": models.AgendaItem},
    ),
    path(
        "attendance/",
        views.MeetingAttendanceListView.as_view(),
        name="meetingattendance_list",
    ),
    path(
        "attendance/add/",
        views.MeetingAttendanceEditView.as_view(),
        name="meetingattendance_add",
    ),
    path(
        "attendance/delete/",
        views.MeetingAttendanceBulkDeleteView.as_view(),
        name="meetingattendance_bulk_delete",
    ),
    path(
        "attendance/<int:pk>/",
        views.MeetingAttendanceView.as_view(),
        name="meetingattendance",
    ),
    path(
        "attendance/<int:pk>/edit/",
        views.MeetingAttendanceEditView.as_view(),
        name="meetingattendance_edit",
    ),
    path(
        "attendance/<int:pk>/delete/",
        views.MeetingAttendanceDeleteView.as_view(),
        name="meetingattendance_delete",
    ),
    path(
        "attendance/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="meetingattendance_changelog",
        kwargs={"model": models.MeetingAttendance},
    ),
    path(
        "owner-snapshots/",
        views.MeetingOwnerSnapshotListView.as_view(),
        name="meetingownersnapshot_list",
    ),
    path(
        "owner-snapshots/<int:pk>/",
        views.MeetingOwnerSnapshotView.as_view(),
        name="meetingownersnapshot",
    ),
    path(
        "attendance-events/",
        views.MeetingAttendanceEventListView.as_view(),
        name="meetingattendanceevent_list",
    ),
    path(
        "attendance-events/add/",
        views.MeetingAttendanceEventEditView.as_view(),
        name="meetingattendanceevent_add",
    ),
    path(
        "attendance-events/delete/",
        views.MeetingAttendanceEventBulkDeleteView.as_view(),
        name="meetingattendanceevent_bulk_delete",
    ),
    path(
        "attendance-events/<int:pk>/",
        views.MeetingAttendanceEventView.as_view(),
        name="meetingattendanceevent",
    ),
    path(
        "attendance-events/<int:pk>/edit/",
        views.MeetingAttendanceEventEditView.as_view(),
        name="meetingattendanceevent_edit",
    ),
    path(
        "attendance-events/<int:pk>/delete/",
        views.MeetingAttendanceEventDeleteView.as_view(),
        name="meetingattendanceevent_delete",
    ),
    path(
        "attendance-events/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="meetingattendanceevent_changelog",
        kwargs={"model": models.MeetingAttendanceEvent},
    ),
    path("votes/", views.VoteListView.as_view(), name="vote_list"),
    path("votes/add/", views.VoteEditView.as_view(), name="vote_add"),
    path("votes/delete/", views.VoteBulkDeleteView.as_view(), name="vote_bulk_delete"),
    path("votes/<int:pk>/", views.VoteView.as_view(), name="vote"),
    path("votes/<int:pk>/edit/", views.VoteEditView.as_view(), name="vote_edit"),
    path("votes/<int:pk>/delete/", views.VoteDeleteView.as_view(), name="vote_delete"),
    path(
        "votes/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="vote_changelog",
        kwargs={"model": models.Vote},
    ),
    path(
        "vote-sessions/",
        views.AgendaVoteSessionListView.as_view(),
        name="agendavotesession_list",
    ),
    path(
        "vote-sessions/<int:pk>/",
        views.AgendaVoteSessionView.as_view(),
        name="agendavotesession",
    ),
    path(
        "vote-sessions/<int:pk>/delete/",
        views.AgendaVoteSessionDeleteView.as_view(),
        name="agendavotesession_delete",
    ),
    path(
        "vote-sessions/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="agendavotesession_changelog",
        kwargs={"model": models.AgendaVoteSession},
    ),
    path(
        "vote-ballots/",
        views.AgendaVoteBallotListView.as_view(),
        name="agendavoteballot_list",
    ),
    path(
        "vote-ballots/<int:pk>/",
        views.AgendaVoteBallotView.as_view(),
        name="agendavoteballot",
    ),
    path(
        "vote-ballots/<int:pk>/delete/",
        views.AgendaVoteBallotDeleteView.as_view(),
        name="agendavoteballot_delete",
    ),
    path(
        "vote-ballots/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="agendavoteballot_changelog",
        kwargs={"model": models.AgendaVoteBallot},
    ),
    path(
        "vote-weight-styles/",
        views.VoteWeightStyleListView.as_view(),
        name="voteweightstyle_list",
    ),
    path(
        "vote-weight-styles/sync-current/",
        views.VoteWeightStyleSyncCurrentView.as_view(),
        name="voteweightstyle_sync_current",
    ),
    path(
        "vote-weight-styles/add/",
        views.VoteWeightStyleEditView.as_view(),
        name="voteweightstyle_add",
    ),
    path(
        "vote-weight-styles/delete/",
        views.VoteWeightStyleBulkDeleteView.as_view(),
        name="voteweightstyle_bulk_delete",
    ),
    path(
        "vote-weight-styles/<int:pk>/",
        views.VoteWeightStyleView.as_view(),
        name="voteweightstyle",
    ),
    path(
        "vote-weight-styles/<int:pk>/edit/",
        views.VoteWeightStyleEditView.as_view(),
        name="voteweightstyle_edit",
    ),
    path(
        "vote-weight-styles/<int:pk>/delete/",
        views.VoteWeightStyleDeleteView.as_view(),
        name="voteweightstyle_delete",
    ),
    path(
        "vote-weight-styles/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="voteweightstyle_changelog",
        kwargs={"model": models.VoteWeightStyle},
    ),
    path(
        "minutes/", views.MeetingMinutesListView.as_view(), name="meetingminutes_list"
    ),
    path(
        "minutes/add/",
        views.MeetingMinutesEditView.as_view(),
        name="meetingminutes_add",
    ),
    path(
        "minutes/delete/",
        views.MeetingMinutesBulkDeleteView.as_view(),
        name="meetingminutes_bulk_delete",
    ),
    path(
        "minutes/<int:pk>/", views.MeetingMinutesView.as_view(), name="meetingminutes"
    ),
    path(
        "minutes/<int:pk>/edit/",
        views.MeetingMinutesEditView.as_view(),
        name="meetingminutes_edit",
    ),
    path(
        "minutes/<int:pk>/delete/",
        views.MeetingMinutesDeleteView.as_view(),
        name="meetingminutes_delete",
    ),
    path(
        "minutes/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="meetingminutes_changelog",
        kwargs={"model": models.MeetingMinutes},
    ),
    path(
        "invitations/",
        views.MeetingInvitationListView.as_view(),
        name="meetinginvitation_list",
    ),
    path(
        "invitations/add/",
        views.MeetingInvitationEditView.as_view(),
        name="meetinginvitation_add",
    ),
    path(
        "invitations/delete/",
        views.MeetingInvitationBulkDeleteView.as_view(),
        name="meetinginvitation_bulk_delete",
    ),
    path(
        "invitations/<int:pk>/",
        views.MeetingInvitationView.as_view(),
        name="meetinginvitation",
    ),
    path(
        "invitations/<int:pk>/edit/",
        views.MeetingInvitationEditView.as_view(),
        name="meetinginvitation_edit",
    ),
    path(
        "invitations/<int:pk>/delete/",
        views.MeetingInvitationDeleteView.as_view(),
        name="meetinginvitation_delete",
    ),
    path(
        "invitations/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="meetinginvitation_changelog",
        kwargs={"model": models.MeetingInvitation},
    ),
]
