steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - NETBOX_VERSION=${_NETBOX_VERSION}
      - --file
      - Dockerfile.production
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY