# Generated by Django 6.0.3 on 2026-03-04 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('flat_number', models.CharField(help_text='Apartment number within the building', max_length=20, verbose_name='Flat number')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Floor')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Area (m²)')),
                ('disposition', models.CharField(blank=True, default='', help_text='e.g. 2+1, 3+kk', max_length=20, verbose_name='Disposition')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flats', to='buildings.building', verbose_name='Building')),
            ],
            options={
                'verbose_name': 'Flat',
                'verbose_name_plural': 'Flats',
                'ordering': ['building', 'flat_number'],
                'abstract': False,
                'unique_together': {('building', 'flat_number')},
            },
        ),
    ]
