# Generated by Django 6.0.3 on 2026-03-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='cellar_unit',
            field=models.CharField(blank=True, default='', help_text='Cellar / storage unit number', max_length=50, verbose_name='Cellar unit'),
        ),
        migrations.AddField(
            model_name='flat',
            name='gas_installed',
            field=models.BooleanField(default=False, verbose_name='Gas installed'),
        ),
        migrations.AddField(
            model_name='flat',
            name='has_balcony',
            field=models.BooleanField(default=False, verbose_name='Has balcony'),
        ),
        migrations.AddField(
            model_name='flat',
            name='number_of_rooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of rooms'),
        ),
        migrations.AddField(
            model_name='flat',
            name='ownership_cert_number',
            field=models.CharField(blank=True, default='', help_text='Číslo listu vlastnictví', max_length=100, verbose_name='Ownership certificate number'),
        ),
        migrations.AddField(
            model_name='flat',
            name='radiator_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Radiator count'),
        ),
        migrations.AddField(
            model_name='flat',
            name='radiator_power_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Radiator power (kW)'),
        ),
        migrations.AddField(
            model_name='flat',
            name='waste_outlets',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Waste outlets'),
        ),
        migrations.AddField(
            model_name='flat',
            name='water_outlets',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Water outlets'),
        ),
    ]
