# Generated by Django 6.0.3 on 2026-03-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0002_flat_cellar_unit_flat_gas_installed_flat_has_balcony_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="cuzk_share_denominator",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Podíl na společných částech domu — jmenovatel (z ČÚZK)",
                null=True,
                verbose_name="CUZK share denominator",
            ),
        ),
        migrations.AddField(
            model_name="flat",
            name="cuzk_share_numerator",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Podíl na společných částech domu — čitatel (z ČÚZK)",
                null=True,
                verbose_name="CUZK share numerator",
            ),
        ),
        migrations.AddField(
            model_name="flat",
            name="cuzk_unit_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Unikátní identifikátor jednotky v ISKN (ČÚZK)",
                null=True,
                unique=True,
                verbose_name="CUZK unit ID",
            ),
        ),
    ]
