# Generated by Django 5.2.13 on 2026-08-08 09:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import netbox.models.deletion
import solomon_facilities.models
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("extras", "0134_owner"),
        ("solomon_property", "0006_remove_propertyowner_email_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("number", models.SmallIntegerField()),
                ("reference", models.CharField(max_length=20)),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "elevation_m",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                (
                    "height_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "building_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facility_levels",
                        to="solomon_property.buildingobject",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Building level",
                "verbose_name_plural": "Building levels",
                "ordering": ("building_object", "number"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Door",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("reference", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("door_type", models.CharField(default="interior", max_length=20)),
                ("fire_rating", models.CharField(blank=True, max_length=50)),
                ("emergency_exit", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doors",
                        to="solomon_facilities.buildinglevel",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Door",
                "verbose_name_plural": "Doors",
                "ordering": ("level", "reference"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FloorPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        default=1600,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        default=900,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("measurement_unit", models.CharField(default="cm", max_length=2)),
                ("notes", models.TextField(blank=True)),
                (
                    "level",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan",
                        to="solomon_facilities.buildinglevel",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Floor plan",
                "verbose_name_plural": "Floor plans",
                "ordering": ("level",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="KeyCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("inventory_code", models.CharField(max_length=100, unique=True)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(default="available", max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Physical key",
                "verbose_name_plural": "Physical keys",
                "ordering": ("profile", "inventory_code"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="KeyIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("external_holder", models.CharField(blank=True, max_length=200)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("purpose", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "key_copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="solomon_facilities.keycopy",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="key_issues",
                        to="solomon_property.person",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Key issue",
                "verbose_name_plural": "Key issues",
                "ordering": ("-issued_at",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="KeyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "building_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="key_profiles",
                        to="solomon_property.buildingobject",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Key profile",
                "verbose_name_plural": "Key profiles",
                "ordering": ("building_object", "code"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="keycopy",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="copies",
                to="solomon_facilities.keyprofile",
            ),
        ),
        migrations.CreateModel(
            name="LockCylinder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=100)),
                ("active_from", models.DateField(blank=True, null=True)),
                ("active_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "door",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locks",
                        to="solomon_facilities.door",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lock cylinder",
                "verbose_name_plural": "Lock cylinders",
                "ordering": ("door", "name"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="KeyProfileLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "key_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solomon_facilities.keyprofile",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "lock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solomon_facilities.lockcylinder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Key profile lock",
                "verbose_name_plural": "Key profile locks",
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="keyprofile",
            name="locks",
            field=models.ManyToManyField(
                related_name="key_profiles",
                through="solomon_facilities.KeyProfileLock",
                to="solomon_facilities.lockcylinder",
            ),
        ),
        migrations.CreateModel(
            name="PlanRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(default="draft", max_length=20)),
                (
                    "source_file",
                    models.FileField(
                        blank=True, upload_to=solomon_facilities.models.plan_upload_path
                    ),
                ),
                (
                    "background_file",
                    models.FileField(
                        blank=True, upload_to=solomon_facilities.models.plan_upload_path
                    ),
                ),
                ("source_page", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "scale_denominator",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("source_note", models.TextField(blank=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="solomon_facilities.floorplan",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan revision",
                "verbose_name_plural": "Plan revisions",
                "ordering": ("plan", "-revision"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="floorplan",
            name="active_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_plans",
                to="solomon_facilities.planrevision",
            ),
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("reference", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("kind", models.CharField(max_length=30)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "area_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facility_spaces",
                        to="solomon_property.building",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spaces",
                        to="solomon_facilities.buildinglevel",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="solomon_facilities.space",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Space",
                "verbose_name_plural": "Spaces",
                "ordering": ("level", "building", "reference"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="door",
            name="from_space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doors_from",
                to="solomon_facilities.space",
            ),
        ),
        migrations.AddField(
            model_name="door",
            name="to_space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doors_to",
                to="solomon_facilities.space",
            ),
        ),
        migrations.CreateModel(
            name="SpaceFlatAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("role", models.CharField(max_length=30)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "flat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="space_assignments",
                        to="solomon_property.flat",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flat_assignments",
                        to="solomon_facilities.space",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Space-to-flat assignment",
                "verbose_name_plural": "Space-to-flat assignments",
                "ordering": ("space", "flat"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SpaceUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("usage_type", models.CharField(default="rental", max_length=20)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="space_usages",
                        to="solomon_property.propertyowner",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="space_usages",
                        to="solomon_property.person",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usages",
                        to="solomon_facilities.space",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Space usage",
                "verbose_name_plural": "Space usages",
                "ordering": ("space", "-effective_from"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TechnicalAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("asset_type", models.CharField(max_length=100)),
                ("status", models.CharField(default="active", max_length=20)),
                ("emergency_instructions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technical_assets",
                        to="solomon_facilities.buildinglevel",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="solomon_facilities.technicalasset",
                    ),
                ),
                (
                    "serves_flats",
                    models.ManyToManyField(
                        blank=True,
                        related_name="technical_assets",
                        to="solomon_property.flat",
                    ),
                ),
                (
                    "serves_spaces",
                    models.ManyToManyField(
                        blank=True,
                        related_name="served_by_assets",
                        to="solomon_facilities.space",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technical_assets",
                        to="solomon_facilities.space",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Technical asset",
                "verbose_name_plural": "Technical assets",
                "ordering": ("system", "code"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PlanElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("element_type", models.CharField(max_length=20)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("geometry", models.JSONField(default=dict)),
                ("style", models.JSONField(blank=True, default=dict)),
                ("z_index", models.IntegerField(default=0)),
                ("locked", models.BooleanField(default=False)),
                (
                    "door",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_elements",
                        to="solomon_facilities.door",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="solomon_facilities.planrevision",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_elements",
                        to="solomon_facilities.space",
                    ),
                ),
                (
                    "technical_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_elements",
                        to="solomon_facilities.technicalasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan element",
                "verbose_name_plural": "Plan elements",
                "ordering": ("revision", "z_index", "pk"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TechnicalConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("kind", models.CharField(default="feeds", max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "from_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connections",
                        to="solomon_facilities.technicalasset",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "to_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connections",
                        to="solomon_facilities.technicalasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technical connection",
                "verbose_name_plural": "Technical connections",
                "ordering": ("from_asset", "to_asset"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TechnicalSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("kind", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True)),
                (
                    "building_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technical_systems",
                        to="solomon_property.buildingobject",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Technical system",
                "verbose_name_plural": "Technical systems",
                "ordering": ("building_object", "kind", "name"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="technicalasset",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="solomon_facilities.technicalsystem",
            ),
        ),
        migrations.AddConstraint(
            model_name="buildinglevel",
            constraint=models.UniqueConstraint(
                fields=("building_object", "number"),
                name="solomon_facilities_unique_level_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="buildinglevel",
            constraint=models.UniqueConstraint(
                fields=("building_object", "reference"),
                name="solomon_facilities_unique_level_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="keyissue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("returned_at__isnull", True)),
                fields=("key_copy",),
                name="solomon_facilities_one_active_key_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="lockcylinder",
            constraint=models.UniqueConstraint(
                fields=("door", "name"), name="solomon_facilities_unique_lock_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="keyprofilelock",
            constraint=models.UniqueConstraint(
                fields=("key_profile", "lock"),
                name="solomon_facilities_unique_key_profile_lock",
            ),
        ),
        migrations.AddConstraint(
            model_name="keyprofile",
            constraint=models.UniqueConstraint(
                fields=("building_object", "code"),
                name="solomon_facilities_unique_key_profile_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="planrevision",
            constraint=models.UniqueConstraint(
                fields=("plan", "revision"),
                name="solomon_facilities_unique_plan_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="space",
            constraint=models.UniqueConstraint(
                fields=("level", "reference"),
                name="solomon_facilities_unique_space_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="door",
            constraint=models.UniqueConstraint(
                fields=("level", "reference"),
                name="solomon_facilities_unique_door_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="spaceflatassignment",
            constraint=models.UniqueConstraint(
                fields=("space", "flat", "role", "effective_from"),
                name="solomon_facilities_unique_space_flat_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="technicalconnection",
            constraint=models.UniqueConstraint(
                fields=("from_asset", "to_asset", "kind"),
                name="solomon_facilities_unique_asset_connection",
            ),
        ),
        migrations.AddConstraint(
            model_name="technicalsystem",
            constraint=models.UniqueConstraint(
                fields=("building_object", "name"),
                name="solomon_facilities_unique_system_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="technicalasset",
            constraint=models.UniqueConstraint(
                fields=("system", "code"), name="solomon_facilities_unique_asset_code"
            ),
        ),
    ]
