# Generated by Django 5.2.13 on 2026-08-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solomon_facilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planrevision",
            name="background_rotation",
            field=models.SmallIntegerField(default=0),
        ),
    ]
