# Generated by Django 5.2.13 on 2026-08-31 19:11

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import solomon_issues.models
import solomon_issues.utils
import taggit.managers
import utilities.fields
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0134_owner"),
        ("users", "0015_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=32, unique=True)),
                ("label", models.CharField(max_length=200)),
                (
                    "assigned_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("location_hint", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(default="active", max_length=20)),
                ("print_instructions", models.CharField(blank=True, max_length=200)),
                ("public_description", models.TextField(blank=True)),
                ("allow_public_reports", models.BooleanField(default=True)),
                ("show_open_issues", models.BooleanField(default=True)),
                ("require_reporter_contact", models.BooleanField(default=False)),
                ("default_priority", models.CharField(default="normal", max_length=20)),
                (
                    "notify_emails",
                    models.TextField(
                        blank=True,
                        validators=[solomon_issues.utils.validate_email_list],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_tags",
                        to="users.group",
                    ),
                ),
                (
                    "assigned_object_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset tag",
                "verbose_name_plural": "Asset tags",
                "ordering": ["label", "code"],
                "permissions": (("print_assettag", "Can render and print QR labels"),),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "assigned_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("status", models.CharField(default="new", max_length=20)),
                ("priority", models.CharField(default="normal", max_length=20)),
                ("source", models.CharField(default="qr", max_length=20)),
                ("reporter_name", models.CharField(blank=True, max_length=120)),
                ("reporter_email", models.EmailField(blank=True, max_length=254)),
                ("reporter_phone", models.CharField(blank=True, max_length=40)),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=64, unique=True),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("notify_reporter", models.BooleanField(default=True)),
                (
                    "asset_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="solomon_issues.assettag",
                    ),
                ),
                (
                    "assigned_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to="users.group",
                    ),
                ),
                (
                    "assigned_object_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="solomon_issues.issue",
                    ),
                ),
                (
                    "reporter_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue",
                "verbose_name_plural": "Issues",
                "ordering": ["-created"],
                "permissions": (
                    (
                        "manage_issue",
                        "Can change issue status, assignment and resolution",
                    ),
                    ("view_internal_issue", "Can view internal notes on issues"),
                    (
                        "report_issue",
                        "Can report problems even when anonymous reporting is disabled",
                    ),
                ),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="IssueAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=solomon_issues.models.attachment_upload_path
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("uploader_name", models.CharField(blank=True, max_length=120)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="solomon_issues.issue",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue attachment",
                "verbose_name_plural": "Issue attachments",
                "ordering": ["created", "pk"],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="IssueCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("color", utilities.fields.ColorField(default="9e9e9e", max_length=6)),
                ("default_priority", models.CharField(default="normal", max_length=20)),
                (
                    "notify_emails",
                    models.TextField(
                        blank=True,
                        validators=[solomon_issues.utils.validate_email_list],
                    ),
                ),
                (
                    "response_sla_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "resolution_sla_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_issue_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_issue_categories",
                        to="users.group",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue category",
                "verbose_name_plural": "Issue categories",
                "ordering": ["name"],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="issue",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="solomon_issues.issuecategory",
            ),
        ),
        migrations.AddField(
            model_name="assettag",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asset_tags",
                to="solomon_issues.issuecategory",
            ),
        ),
        migrations.CreateModel(
            name="IssueComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("author_name", models.CharField(blank=True, max_length=120)),
                ("from_reporter", models.BooleanField(default=False)),
                ("visibility", models.CharField(default="public", max_length=20)),
                ("body", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="solomon_issues.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue comment",
                "verbose_name_plural": "Issue comments",
                "ordering": ["created", "pk"],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="IssueEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(max_length=30)),
                ("actor_name", models.CharField(blank=True, max_length=120)),
                ("visibility", models.CharField(default="public", max_length=20)),
                ("message", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="solomon_issues.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue event",
                "verbose_name_plural": "Issue events",
                "ordering": ["created", "pk"],
            },
        ),
        migrations.CreateModel(
            name="IssueNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("event_type", models.CharField(blank=True, max_length=30)),
                ("success", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="solomon_issues.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue notification",
                "verbose_name_plural": "Issue notifications",
                "ordering": ["-sent_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="IssueSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("is_reporter", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("token", models.CharField(blank=True, max_length=64, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="solomon_issues.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue subscriber",
                "verbose_name_plural": "Issue subscribers",
                "ordering": ["email"],
            },
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["status"], name="solomon_iss_status_de3565_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["assigned_object_type", "assigned_object_id"],
                name="solomon_iss_assigne_0079f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assettag",
            index=models.Index(
                fields=["assigned_object_type", "assigned_object_id"],
                name="solomon_iss_assigne_f29fe8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuesubscriber",
            constraint=models.UniqueConstraint(
                fields=("issue", "email"), name="solomon_issues_subscriber_unique"
            ),
        ),
    ]
