# Generated by Django 5.2.12 on 2026-04-01 13:35

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0134_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=20)),
                ('city', models.CharField(default='Praha', max_length=100)),
                ('postal_code', models.CharField(default='14900', max_length=10)),
                ('number_of_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('elevator', models.BooleanField(default=False)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_units', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('land_plot_number', models.CharField(blank=True, max_length=50)),
                ('common_rooms', models.TextField(blank=True)),
                ('floor_plan_url', models.URLField(blank=True)),
                ('common_area_rental', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('cuzk_building_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('cuzk_lv_number', models.IntegerField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('flat_number', models.CharField(max_length=20)),
                ('floor', models.SmallIntegerField(blank=True, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('disposition', models.CharField(blank=True, max_length=10)),
                ('number_of_rooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('water_outlets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('waste_outlets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('radiator_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('radiator_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gas_installed', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('cellar_unit', models.CharField(blank=True, max_length=50)),
                ('ownership_cert_number', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('cuzk_unit_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('cuzk_share_numerator', models.IntegerField(blank=True, null=True)),
                ('cuzk_share_denominator', models.IntegerField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flats', to='solomon_property.building')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Flat',
                'verbose_name_plural': 'Flats',
                'ordering': ['building', 'flat_number'],
                'unique_together': {('building', 'flat_number')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title_before', models.CharField(blank=True, max_length=50)),
                ('title_after', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('contact_address', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ['last_name', 'first_name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('display_name', models.CharField(max_length=300)),
                ('person_type', models.CharField(default='natural', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('permanent_address', models.TextField(blank=True)),
                ('contact_address', models.TextField(blank=True)),
                ('deputy_name', models.CharField(blank=True, max_length=200)),
                ('deputy_contact', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('cuzk_owner_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('persons', models.ManyToManyField(blank=True, related_name='ownerships', to='solomon_property.person')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Property Owner',
                'verbose_name_plural': 'Property Owners',
                'ordering': ['display_name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PropertyTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='solomon_property.flat')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='solomon_property.person')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Property Tenant',
                'verbose_name_plural': 'Property Tenants',
                'ordering': ['flat', 'effective_from'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FlatOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('share_numerator', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('share_denominator', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flat_owners', to='solomon_property.flat')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flat_owners', to='solomon_property.propertyowner')),
            ],
            options={
                'verbose_name': 'Flat ownership',
                'verbose_name_plural': 'Flat ownerships',
                'ordering': ['flat', 'effective_from'],
                'unique_together': {('flat', 'owner', 'effective_from')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
