# Generated by Django 5.2.12 on 2026-04-01 19:42

import django.contrib.postgres.fields
from django.db import migrations, models


def copy_email_phone_to_arrays(apps, schema_editor):
    """Copy existing email/phone values into the new ArrayField columns."""
    Person = apps.get_model('solomon_property', 'Person')
    for person in Person.objects.all():
        emails = [person.email] if person.email else []
        phones = [person.phone] if person.phone else []
        Person.objects.filter(pk=person.pk).update(emails=emails, phones=phones)


class Migration(migrations.Migration):

    dependencies = [
        ('solomon_property', '0001_initial'),
    ]

    operations = [
        # 1. Add new array fields (keeping old fields intact)
        migrations.AddField(
            model_name='person',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True, default=list, size=None,
            ),
        ),
        migrations.AddField(
            model_name='person',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30),
                blank=True, default=list, size=None,
            ),
        ),
        # 2. Copy data from old fields to new arrays
        migrations.RunPython(
            copy_email_phone_to_arrays,
            migrations.RunPython.noop,
        ),
        # 3. Remove old single-value fields
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
    ]
