# Generated by Django 5.2.12 on 2026-04-30

import django.contrib.postgres.fields
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models



def _to_house_number(value):
    if value is None:
        return None
    text = str(value).strip()
    return int(text) if text.isdigit() else None



def populate_building_objects(apps, _schema_editor):
    Building = apps.get_model("solomon_property", "Building")
    BuildingObject = apps.get_model("solomon_property", "BuildingObject")

    by_cuzk = {}
    without_cuzk = []

    for building in Building.objects.all().order_by("id"):
        if building.cuzk_building_id:
            by_cuzk.setdefault(building.cuzk_building_id, []).append(building)
        else:
            without_cuzk.append(building)

    for cuzk_id, buildings in by_cuzk.items():
        first = buildings[0]
        house_numbers = []
        for item in buildings:
            parsed_house_number = _to_house_number(item.house_number)
            if parsed_house_number is not None and parsed_house_number not in house_numbers:
                house_numbers.append(parsed_house_number)

        obj = BuildingObject.objects.create(
            name=f"SO {cuzk_id}",
            cuzk_building_id=cuzk_id,
            municipality_name=first.city or "",
            city_part_name=first.street or "",
            lv_number=first.cuzk_lv_number,
            house_numbers=house_numbers,
        )

        Building.objects.filter(id__in=[b.id for b in buildings]).update(building_object=obj)

    for building in without_cuzk:
        parsed_house_number = _to_house_number(building.house_number)
        obj = BuildingObject.objects.create(
            name=f"{building.city} {building.street}".strip() or building.name,
            municipality_name=building.city or "",
            city_part_name=building.street or "",
            house_numbers=[parsed_house_number] if parsed_house_number is not None else [],
        )
        building.building_object = obj
        building.save(update_fields=["building_object"])



def noop_reverse(_apps, _schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("solomon_property", "0002_convert_person_email_phone_to_arrays"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingObject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("custom_field_data", models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ("name", models.CharField(max_length=200)),
                ("cuzk_building_id", models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ("building_type_name", models.CharField(blank=True, max_length=200)),
                ("usage_name", models.CharField(blank=True, max_length=200)),
                ("municipality_name", models.CharField(blank=True, max_length=100)),
                ("city_part_name", models.CharField(blank=True, max_length=100)),
                ("lv_number", models.IntegerField(blank=True, null=True)),
                ("cadastral_territory_name", models.CharField(blank=True, max_length=100)),
                (
                    "house_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Building object",
                "verbose_name_plural": "Building objects",
                "ordering": ["name"],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="building",
            name="building_object",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="buildings", to="solomon_property.buildingobject"),
        ),
        migrations.RunPython(populate_building_objects, noop_reverse),
        migrations.AlterField(
            model_name="building",
            name="building_object",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="buildings", to="solomon_property.buildingobject"),
        ),
    ]
