# Generated by Django 5.2.12 on 2026-08-07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("solomon_property", "0005_objectpermission_compatible_codenames"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyowner",
            name="email",
        ),
        migrations.RemoveField(
            model_name="propertyowner",
            name="phone",
        ),
    ]
