# Generated by Django 5.2.12 on 2026-04-11 12:00

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solomon_meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendaitem",
            name="presenter",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="agendaitem",
            name="quorum_threshold",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.5000"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="invitation_pdf_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="invitation_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="owner_snapshot_taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="phase",
            field=models.CharField(default="PLANNING", max_length=20),
        ),
        migrations.AddField(
            model_name="meeting",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AgendaVoteSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("negative_form", models.BooleanField(default=False)),
                ("present_weight", models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=12)),
                ("quorum_met", models.BooleanField(default=False)),
                ("result", models.CharField(default="N/A", max_length=20)),
                (
                    "agenda_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_sessions",
                        to="solomon_meetings.agendaitem",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Agenda vote session",
                "verbose_name_plural": "Agenda vote sessions",
                "ordering": ["agenda_item", "-started_at"],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MeetingOwnerSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("owner_display_name", models.CharField(max_length=255)),
                ("flat_label", models.CharField(blank=True, max_length=255)),
                ("representation", models.CharField(default="ABSENT", max_length=10)),
                ("proxy_name", models.CharField(blank=True, max_length=255)),
                ("share_numerator", models.PositiveIntegerField()),
                ("share_denominator", models.PositiveIntegerField()),
                ("share_value", models.DecimalField(decimal_places=6, max_digits=12)),
                ("unit_count", models.PositiveIntegerField(default=1)),
                ("ballot_label", models.CharField(blank=True, max_length=32)),
                ("ballot_color", models.CharField(blank=True, max_length=7)),
                ("snapshot_taken_at", models.DateTimeField()),
                ("first_arrived_at", models.DateTimeField(blank=True, null=True)),
                ("last_left_at", models.DateTimeField(blank=True, null=True)),
                ("is_currently_present", models.BooleanField(default=False)),
                (
                    "flat_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meeting_owner_snapshots",
                        to="solomon_property.flatowner",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_snapshots",
                        to="solomon_meetings.meeting",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meeting_owner_snapshots",
                        to="solomon_property.propertyowner",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Meeting owner snapshot",
                "verbose_name_plural": "Meeting owner snapshots",
                "ordering": ["meeting", "owner_display_name", "flat_label"],
                "unique_together": {("meeting", "flat_owner")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AgendaVoteBallot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("label", models.CharField(blank=True, max_length=32)),
                ("color", models.CharField(blank=True, max_length=7)),
                ("share_value", models.DecimalField(decimal_places=6, max_digits=12)),
                ("issued_count", models.PositiveIntegerField(default=0)),
                ("for_count", models.PositiveIntegerField(default=0)),
                ("against_count", models.PositiveIntegerField(default=0)),
                ("abstain_count", models.PositiveIntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballot_rows",
                        to="solomon_meetings.agendavotesession",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Agenda vote ballot row",
                "verbose_name_plural": "Agenda vote ballot rows",
                "ordering": ["session", "share_value", "label"],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MeetingAttendanceEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("event_type", models.CharField(max_length=10)),
                ("event_time", models.DateTimeField()),
                ("source", models.CharField(default="manual", max_length=32)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="solomon_meetings.meetingownersnapshot",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Meeting attendance event",
                "verbose_name_plural": "Meeting attendance events",
                "ordering": ["snapshot", "event_time", "created"],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]