# Generated by GitHub Copilot on 2026-04-27

from collections import defaultdict
from decimal import Decimal
from fractions import Fraction

from django.db import migrations, models


def quantize_weight_fraction(numerator, denominator):
    return (Decimal(numerator) / Decimal(denominator)).quantize(Decimal("0.000001"))


def backfill_vote_weight_style_fractions(apps, schema_editor):
    VoteWeightStyle = apps.get_model("solomon_meetings", "VoteWeightStyle")
    FlatOwner = apps.get_model("solomon_property", "FlatOwner")

    exact_fraction_by_weight = {}
    ownerships = FlatOwner.objects.filter(effective_to__isnull=True).select_related(
        "flat"
    )
    flat_to_ownerships = defaultdict(list)
    for ownership in ownerships:
        flat_to_ownerships[ownership.flat_id].append(ownership)

    for flat_ownerships in flat_to_ownerships.values():
        flat = flat_ownerships[0].flat
        numerator = None
        denominator = None

        if len(flat_ownerships) == 1:
            ownership = flat_ownerships[0]
            numerator = ownership.share_numerator
            denominator = ownership.share_denominator
        elif flat.cuzk_share_numerator and flat.cuzk_share_denominator:
            numerator = flat.cuzk_share_numerator
            denominator = flat.cuzk_share_denominator
        else:
            total = sum(
                (
                    Fraction(o.share_numerator, o.share_denominator)
                    for o in flat_ownerships
                ),
                Fraction(0, 1),
            )
            numerator = total.numerator
            denominator = total.denominator

        if numerator and denominator:
            exact_fraction_by_weight.setdefault(
                quantize_weight_fraction(numerator, denominator),
                (numerator, denominator),
            )

    for style in VoteWeightStyle.objects.all():
        numerator = None
        denominator = None

        if style.voting_method == "BY_UNITS":
            integral_value = int(style.weight_value)
            if Decimal(integral_value) == style.weight_value:
                numerator = integral_value
                denominator = 1
        else:
            numerator, denominator = exact_fraction_by_weight.get(
                style.weight_value, (None, None)
            )

        if not numerator or not denominator:
            fallback = Fraction(style.weight_value).limit_denominator(200000)
            numerator = fallback.numerator
            denominator = fallback.denominator

        style.weight_numerator = numerator
        style.weight_denominator = denominator
        style.save(update_fields=["weight_numerator", "weight_denominator"])


class Migration(migrations.Migration):
    dependencies = [
        ("solomon_meetings", "0002_meeting_workflow_rework"),
        ("solomon_property", "0002_convert_person_email_phone_to_arrays"),
    ]

    operations = [
        migrations.AddField(
            model_name="voteweightstyle",
            name="weight_denominator",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Weight denominator"
            ),
        ),
        migrations.AddField(
            model_name="voteweightstyle",
            name="weight_numerator",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Weight numerator"
            ),
        ),
        migrations.RunPython(
            backfill_vote_weight_style_fractions, migrations.RunPython.noop
        ),
    ]
