# Generated by Django 5.2.12 on 2026-07-05

from decimal import Decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solomon_meetings', '0004_meetingattendanceevent_rename_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='attendance_threshold_50',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.5000'), help_text='Minimum share ratio required to mark 50% attendance as reached.', max_digits=5, validators=[MinValueValidator(Decimal('0')), MaxValueValidator(Decimal('1'))], verbose_name='Attendance threshold 50%'),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='attendance_threshold_two_thirds',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.6667'), help_text='Minimum share ratio required to mark 2/3 attendance as reached.', max_digits=5, validators=[MinValueValidator(Decimal('0')), MaxValueValidator(Decimal('1'))], verbose_name='Attendance threshold 2/3'),
        ),
    ]