# Generated by Django 5.2.12 on 2026-07-07

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solomon_meetings", "0007_model_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="voteweightstyle",
            name="is_current",
            field=models.BooleanField(
                default=True,
                help_text="Marks whether this style is used by current ownership shares.",
                verbose_name="Current style",
            ),
        ),
        migrations.CreateModel(
            name="MeetingBallotTypeSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("share_numerator", models.PositiveIntegerField(verbose_name="Share numerator")),
                ("share_denominator", models.PositiveIntegerField(verbose_name="Share denominator")),
                ("share_value", models.DecimalField(decimal_places=6, max_digits=12, verbose_name="Share value")),
                ("ballot_label", models.CharField(blank=True, max_length=32, verbose_name="Ballot label")),
                ("ballot_color", models.CharField(blank=True, max_length=7, verbose_name="Ballot color")),
                ("snapshot_taken_at", models.DateTimeField(verbose_name="Snapshot taken at")),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballot_type_snapshots",
                        to="solomon_meetings.meeting",
                        verbose_name="Meeting",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Meeting ballot type snapshot",
                "verbose_name_plural": "Meeting ballot type snapshots",
                "ordering": ["meeting", "share_value", "ballot_label"],
                "unique_together": {("meeting", "share_value")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
