# Generated by Django 6.0.3 on 2026-03-04 12:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(help_text="Building name or label, e.g. 'Salounova 1'", max_length=255, verbose_name='Name')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('house_number', models.CharField(help_text='Číslo popisné / orientační', max_length=20, verbose_name='House number')),
                ('city', models.CharField(default='Brno', max_length=255, verbose_name='City')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
