# Generated by Django 6.0.3 on 2026-03-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='common_area_rental',
            field=models.TextField(blank=True, default='', help_text='Information about rented common areas', verbose_name='Common area rental'),
        ),
        migrations.AddField(
            model_name='building',
            name='common_rooms',
            field=models.TextField(blank=True, default='', help_text='Description of common areas (e.g. laundry, bike storage)', verbose_name='Common rooms'),
        ),
        migrations.AddField(
            model_name='building',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='Elevator'),
        ),
        migrations.AddField(
            model_name='building',
            name='floor_plan_url',
            field=models.URLField(blank=True, default='', verbose_name='Floor plan URL'),
        ),
        migrations.AddField(
            model_name='building',
            name='land_plot_number',
            field=models.CharField(blank=True, default='', help_text='Číslo pozemku', max_length=50, verbose_name='Land plot number'),
        ),
        migrations.AddField(
            model_name='building',
            name='number_of_floors',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of floors'),
        ),
        migrations.AddField(
            model_name='building',
            name='total_units',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of flats/units in the building', null=True, verbose_name='Total units'),
        ),
        migrations.AddField(
            model_name='building',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year built'),
        ),
    ]
