# Generated by Django 5.2.12 on 2026-03-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_building_cuzk_building_id_building_cuzk_lv_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='cuzk_building_id',
            field=models.BigIntegerField(blank=True, help_text='Identifikátor stavby v ISKN (ČÚZK). Multiple buildings may share the same ID.', null=True, verbose_name='CUZK building ID'),
        ),
    ]
